#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_Etudiant
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ensat")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void Insertquestions(questions instance);
    partial void Updatequestions(questions instance);
    partial void Deletequestions(questions instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Interface_Etudiant.Properties.Settings.Default.tp6ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<questions> questions
		{
			get
			{
				return this.GetTable<questions>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.questions")]
	public partial class questions : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _ref;
		
		private string _intitule;
		
		private string _option1;
		
		private string _option2;
		
		private string _option3;
		
		private string _option4;
		
		private string _Reponse_correcte;
		
		private System.Nullable<int> _poids;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnrefChanging(System.Nullable<int> value);
    partial void OnrefChanged();
    partial void OnintituleChanging(string value);
    partial void OnintituleChanged();
    partial void Onoption1Changing(string value);
    partial void Onoption1Changed();
    partial void Onoption2Changing(string value);
    partial void Onoption2Changed();
    partial void Onoption3Changing(string value);
    partial void Onoption3Changed();
    partial void Onoption4Changing(string value);
    partial void Onoption4Changed();
    partial void OnReponse_correcteChanging(string value);
    partial void OnReponse_correcteChanged();
    partial void OnpoidsChanging(System.Nullable<int> value);
    partial void OnpoidsChanged();
    #endregion
		
		public questions()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ref", Storage="_ref", DbType="Int")]
		public System.Nullable<int> @ref
		{
			get
			{
				return this._ref;
			}
			set
			{
				if ((this._ref != value))
				{
					this.OnrefChanging(value);
					this.SendPropertyChanging();
					this._ref = value;
					this.SendPropertyChanged("@ref");
					this.OnrefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intitule", DbType="VarChar(60)")]
		public string intitule
		{
			get
			{
				return this._intitule;
			}
			set
			{
				if ((this._intitule != value))
				{
					this.OnintituleChanging(value);
					this.SendPropertyChanging();
					this._intitule = value;
					this.SendPropertyChanged("intitule");
					this.OnintituleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_option1", DbType="VarChar(15)")]
		public string option1
		{
			get
			{
				return this._option1;
			}
			set
			{
				if ((this._option1 != value))
				{
					this.Onoption1Changing(value);
					this.SendPropertyChanging();
					this._option1 = value;
					this.SendPropertyChanged("option1");
					this.Onoption1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_option2", DbType="VarChar(15)")]
		public string option2
		{
			get
			{
				return this._option2;
			}
			set
			{
				if ((this._option2 != value))
				{
					this.Onoption2Changing(value);
					this.SendPropertyChanging();
					this._option2 = value;
					this.SendPropertyChanged("option2");
					this.Onoption2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_option3", DbType="VarChar(15)")]
		public string option3
		{
			get
			{
				return this._option3;
			}
			set
			{
				if ((this._option3 != value))
				{
					this.Onoption3Changing(value);
					this.SendPropertyChanging();
					this._option3 = value;
					this.SendPropertyChanged("option3");
					this.Onoption3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_option4", DbType="VarChar(15)")]
		public string option4
		{
			get
			{
				return this._option4;
			}
			set
			{
				if ((this._option4 != value))
				{
					this.Onoption4Changing(value);
					this.SendPropertyChanging();
					this._option4 = value;
					this.SendPropertyChanged("option4");
					this.Onoption4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reponse_correcte", DbType="VarChar(15)")]
		public string Reponse_correcte
		{
			get
			{
				return this._Reponse_correcte;
			}
			set
			{
				if ((this._Reponse_correcte != value))
				{
					this.OnReponse_correcteChanging(value);
					this.SendPropertyChanging();
					this._Reponse_correcte = value;
					this.SendPropertyChanged("Reponse_correcte");
					this.OnReponse_correcteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poids", DbType="Int")]
		public System.Nullable<int> poids
		{
			get
			{
				return this._poids;
			}
			set
			{
				if ((this._poids != value))
				{
					this.OnpoidsChanging(value);
					this.SendPropertyChanging();
					this._poids = value;
					this.SendPropertyChanged("poids");
					this.OnpoidsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
